### ISSUE TITLE
Collision in styles when using Light mode for Directus admin

### ISSUE THREAD

**Issue by bcartier** [u12206050/directus-extension-api-viewer-module#1]
This module is amazing! Thank you!

Just a heads-up that after installing and having the admin set to Light mode, it there's font colour collision that makes the API Viewer module very difficult to read. I'm not sure if you're planning light-mode support for this module, but even just addressing this small collision would at least make it usable in either Light/Dark mode in the interim.

**Comment by bamboowonder** [comment]
Fantastic module.  Much appreciated.   Echoing above, is there a css override that would make the background white?  As a workaround for now as I can't see the text (monitor brightness turned right down...)

**Comment by u12206050** [comment]
![ToggleColorScheme](https://user-images.githubusercontent.com/6641242/165626648-abac8098-e3ad-474c-b4cb-ac3c3f5c165b.gif)

[Latest Release](https://github.com/u12206050/directus-extension-api-viewer-module/releases/tag/1.1.1)

**Comment by bamboowonder** [comment]
Hmm, this didn't fix it for me.  Tried manually changing theme from dark, to light to default and back again to light.  
While it is dark theme, the api-viewer is readable as the font is more white.  but when I switch to the light theme, the api-viewer background stays black and the font dark grey.

**Comment by adussarps** [comment]
Hello there, the module is really nice, but I kind of have the same issue. How do you switch from dark to light theme?

**Comment by co2nunes** [comment]
Good question, I also can't see the switch. @adussarps Did you manage to find out?

**Comment by u12206050** [comment]
Sorry guys for the very slow response. PRs are most welcome if anyone has the time. Currently it should just follow the same theme setting as directus.

**Comment by co2nunes** [comment]
It's not, at least on Directus 10.3.0, the latest. Thanks for reply :)
