### ISSUE TITLE
Crash on loading

### ISSUE THREAD

**Issue by jeffersonsolorzano** [u12206050/directus-extension-api-viewer-module#11]
Every time i try to load the page, it always crashes when it says 'parsing schema'
Directus version: 10.9.3
No logs available
Self hosted

<img width="1352" alt="image" src="https://github.com/u12206050/directus-extension-api-viewer-module/assets/65744166/1bf55384-f0b1-4d35-9832-cc70c1b106d1">

**Comment by lpil** [comment]
I too am having this problem.
Thank you

**Comment by divStar** [comment]
Sadly, same story 😭 .

**Comment by cristiansimion** [comment]
+1 the above with Edit 4 is very accurate describing the issue and how to make it work - but we don't know the exact cause of it.

**Comment by u12206050** [comment]
There seems to be a better maintained extension out now: https://github.com/Belanchuk/directus-extension-rapidocus
With support for the new cookie authentication.
